게시물 목록 조회 API
Wanted-Pre-Onboarding-Team-E/social-media-integration-feed pull request #14
Opened 2023-10-28 03:10 UTC by tomeee11

🚀 이슈 번호
#7  게시물 목록 조회 API
<br>
게시물 목록 조회 API 
## 💡 변경 이유

<br>

![조회](https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/114478045/07563687-72b0-43d8-8d67-bc27847f128a)

## 🔑 주요 변경사항
위와 동일
<br>
1. 게시물, 해시태그 테이블 생성 API (임시)
2. 게시물 목록 조회 API 생성
## 📷 테스트 결과
HTTP 요청 테스트 결과
![요청](https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/114478045/e50dab05-c11e-4520-b691-8e6aebe70ebc)

2023-10-28 06:53 UTC, kangssu requested changes

2023-10-28 06:53 UTC, kangssu commented on src/feature/hashtag/hashtag.controller.ts
> +  @Post(':post_id')
이건 요구사항에 없지만 해시태그 등록 API를 만든 것일까요?
사실 게시글 목록 조회 API 이슈랑 관련은 없어서 
만약 추후에 요렇게 만들일이 생기신다면 이슈 2개로 분리해서 작업하면 좋을 것 같아요 😄 

그리고 저희 변수명 post_id가 아닌 postId 카멜케이스 입니다!

2023-10-28 06:53 UTC, kangssu commented on src/feature/hashtag/hashtag.controller.ts
> +  create(
create 함수명 직역하면 만든다 가 끝인 것 같아요!
협업하는 팀원들이 본다면 무엇을 만드는거지? 라고 생각하고 안에 코드까지 전부 다 봐야하는 일이 생길 것 같습니다!
createHashtagByPostId 이런식으로 만든다 / 해시태그 / postId 기준으로 이런식으로 만드는게 어떨까요?
(create 함수를 사용하는 controller, service, repository 전부요!)

2023-10-28 06:53 UTC, kangssu commented on src/feature/hashtag/repository/hashtag.repository.ts
> +    // const hashtagAsString = hashtags.toString();
이 주석은 필요할까요?
특정 문구가 아닌 코드 주석은 사용하지 않는다면 지워주세용

2023-10-28 06:53 UTC, kangssu commented on src/feature/hashtag/repository/hashtag.repository.ts
> +      hashtag: '톰',
hashtag를 만드는 API 를 호출할때 전부 '톰'으로 들어가는거 아닌가용?
@Body로 리스폰스 값을 받아야할 것 같습니다!

2023-10-28 06:53 UTC, kangssu commented on src/feature/post/dto/createPost.dto.ts
> +export class CreatePostDto {
Dto에서도 데코레이터 사용하는 것이 좋을 것 같습니다!
아래 예시처럼용 그리고 Dto에서 필수값으로 들어오는지 선택하는 값으로 들어오는지 명시하는 것이 좋아보입니당
생략하면 필수값으로 알고 있지만 선택값과 합쳐있을때는 명시하는 것이 Dto를 봤을때 직관적으로 알 수 있어서용!
```
@IsEnum(PostType)
type!: PostType;
```

2023-10-28 06:53 UTC, kangssu commented on src/feature/post/post.controller.ts
> +  async create(@Body() createPostDto: CreatePostDto) {
Post create도 요구사항에 없지만 만들어놓으신거죠..?
혹시 Promise를 사용하지 않으신 이유가 저희 Post entity명이랑 중복되서 빼신 것일까요?

저희 머지하면 제가 Promise<Post> 를 사용해서 아마 위 메서드명이랑 중복되서 오류 발생할 것 같아요..
메서드 Post랑 Post entity랑요! 저도 Post 메서드 쓰려다가  Post entity랑 명칭이 동일하다는 오류때문에 뺐었거든용..
어찌해야할까요 😮

2023-10-28 06:53 UTC, kangssu commented on src/feature/post/post.controller.ts
> +  async findBy(@Query() getPostDto: GetPostsDto) {
이 함수명만 봐서는 어떤걸 작업하는지 모르겠습니당!
위에 create처럼 구체적으로 명시해주세요! 추가적으로 get~ 이런식으로 시작하는 것이 좋아보일듯합니당
제가 들은바로는 repository 연결시에는 find로 작성하는게 적합하다고 알고 있어요! (왜 이렇게 써야하는지 아직 못찾았지만용..)

2023-10-28 06:53 UTC, kangssu commented on src/feature/post/dto/getPost.dto.ts
> +export class GetPostsDto {
Get은 가져온다의 개념같은데 Dto보단 함수에 적합한 것 같아요!
PostRequestDto? 이런식으로 어떤걸 포함하고 있는 객체를 의미했으면 좋겠습니당 😄 

저희 카멜케이스 쓰기로 했던 것 같은데 order_by -> orderBy 이런식으로 전부 수정해주세용!

2023-10-28 06:53 UTC, kangssu commented on src/feature/post/repository/post.repository.ts
> +      } else if (getPostDto.search_by === 'title,content') {
'title,content' 이거 가능한가요..? 
제가 이해한건 searchBy 기준으로 title 또는 content 또는 title&&content 이런식으로 이해를 했는데
tilte과 content는 테이블에 다른 컬럼으로 저장이 되고 있어서 이 부분이 잘 이해가 되지 않습니당!

조건문을 && 조건문 써야하는거 아닌가용??

2023-10-28 09:09 UTC, tomeee11 commented on src/feature/hashtag/hashtag.controller.ts
> +  @Post(':post_id')
아 차후에 만들일이 생긴다면 수정하겠습니다.
자꾸 타입이 변경되서 저장이 되어서 이거저거 테스트 해본다고 임시로 만들었습니다.

2023-10-28 09:10 UTC, tomeee11 commented on src/feature/hashtag/hashtag.controller.ts
> +  create(
해시태그는 신경 안쓰셔두 될거같아요 타입 변경 버그인지 그런거 떄문에 만든거라

2023-10-28 09:12 UTC, tomeee11 commented on src/feature/post/repository/post.repository.ts
> +      } else if (getPostDto.search_by === 'title,content') {
네 잘됩니다

2023-10-28 09:17 UTC, tomeee11 commented on src/feature/post/post.controller.ts
> +  async create(@Body() createPostDto: CreatePostDto) {
저번에도 말씀드렸는데 겹치는 부분 여쭤봣었는데 그냥 쓰시기로 하셔서 일단 납둔 부분도 있고 
해당 크리에이트 부분은 해시태그와 동일하게 타입 변경 문제가 있나 만들어 본거라 
임시 입니다

2023-10-28 09:20 UTC, tomeee11 commented on src/feature/post/post.controller.ts
> +  async findBy(@Query() getPostDto: GetPostsDto) {
차후에 모두 합쳐졌을 때,
한번에 리팩토링하려고 임시방편으로 지정해두었습니다,
(쿼리로 받는 값이 많아서 이름을 어떻게 지어야 할지 고민도 되고요 추천 부탁드립니다.)

2023-10-28 09:21 UTC, tomeee11 commented on src/feature/post/dto/getPost.dto.ts
> +export class GetPostsDto {
위 답변과 동일합니다 .

2023-10-28 10:11 UTC, dawwson commented on src/feature/post/post.controller.ts
> +  async findBy(@Query() getPostDto: GetPostsDto) {
전체 조회인 경우 getAllXXX, 상세 조회인 경우 getDetailXXX 이런 식으로 작성하는 것은 어떠신가요?

2023-10-28 10:49 UTC, tomeee11 commented on src/feature/post/post.controller.ts
> +  async findBy(@Query() getPostDto: GetPostsDto) {
후자로 그럼 수정할게요

2023-10-28 10:50 UTC, kangssu commented on src/feature/post/post.controller.ts
> +  async create(@Body() createPostDto: CreatePostDto) {
@tomeee11 
그때 오류가 안 난다고 들었던 것 같은데 오류가 나서 아예 사용 못하더라구요! 😢 
근데 이 부분은 테스트용이라고 하셨던 것 같은데 나중에 머지 전에만 꼭! 지워주세요!  🙏

2023-10-28 10:56 UTC, kangssu commented on src/feature/post/post.controller.ts
> +  async findBy(@Query() getPostDto: GetPostsDto) {
저도 전체 조회는 아래 2개 중에 선택하는 것이 좋아보입니당 😄 
1. getAllPosts -> getAllPostsByXXX : By까지 추가하는게 해당 API에 맞아보이긴해요 조건들이 걸려서용
2. getPosts -> getPostsByXXX

하나의 게시글을 조회할 경우에는 getPostById 이런식으로 하는 것이 좋아보여요!

2023-10-29 06:48 UTC, laetipark approved these changes
고생 많으십니다! 코드 잘 확인하고 갑니다 :)

2023-10-29 08:51 UTC, kangssu reviewed
여기 레포지토리 전부 분리되어있는데 저희 오늘 오전에 회의한걸로 전부 수정부탁드려요!
그리고 cratePost.dto.ts / getPost.dto.ts / hashtag.repository (hashtag 관련 파일들) 안에 내용이 없는데 사용하지 않는 함수나 파일들은 전부 삭제부탁드려요! 🙏

2023-10-30 00:24 UTC, dawwson commented on src/feature/post/post.service.ts
> +    query.skip(page * page_count).take(page_count);
여기 camel case로 맞춰주셔야겠습니다!

2023-10-30 00:44 UTC, kangssu approved these changes

2023-10-30 00:44 UTC, dawwson approved these changes

2023-10-30 00:44 UTC, laetipark approved these changes

2023-10-30 00:44 UTC, sayapin1 approved these changes
고생하셨습니다 :)

2023-10-30 01:16 UTC, merged