Feature/users/6 sign up
Wanted-Pre-Onboarding-Team-E/social-media-integration-feed pull request #16
Opened 2023-10-28 07:37 UTC by laetipark

## #️⃣ 이슈 번호 또는 링크

#5 사용자 회원가입 API
<br>

## 💡 변경 이유

`POST /user/signup`, 사용자 회원 가입 기능 추가

<br>

## 🔑 주요 변경사항

1. 해시 라이브러리 `bcrypt`, `@types/bcrypt(-D)` 설치
2. 유효성 검사 라이브러리 `class-transformer`, `class-validator` 설치
3. 전역 스코프에서 validation pipe 사용을 위해 `useGlobalPipes` 추가
4. `POST /user/signup`을 통해 회원 가입 진행 (auth, feature/user)

<br>

## 📷 테스트 결과

### 🧪 단위 테스트

<img width="459" alt="스크린샷 2023-10-28 150340" src="https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/68440583/dd49599f-5a01-4385-8487-54ac48d7e4e3">

### 🌐 HTTP 요청 테스트

`POST /user/signup`

#### Request(Body)

```json
{
  "email": "creator98@naver.com",
  "username": "creator98",
  "password": "h12334545d@"
}
```

#### Response(201)

```json
{
  "message": "가입요청이 완료되었습니다.",
  "data": {
    "email": "creator98@naver.com",
    "username": "creator98",
    "password": "h12334545d@"
  }
}
```

#### ERROR(400)

- 이미 존재하는 계정

```json
{
  "message": "creator98은 이미 존재하는 계정입니다.",
  "error": "Bad Request",
  "statusCode": 400
}
```

- 유효하지 않은 이메일

```json
{
  "message": [
    "email must be an email"
  ],
  "error": "Bad Request",
  "statusCode": 400
}
```

- 비밀번호가 10자 미만

```json
{
  "message": [
    "password must be longer than or equal to 10 characters"
  ],
  "error": "Bad Request",
  "statusCode": 400
}
```

- 숫자, 문자, 특수문자 중 2가지 미만 포함 시 또는 3회 이상 연속되는 문자 사용

```json
{
  "message": "적절하지 않은 패스워드 입니다.",
  "error": "Bad Request",
  "statusCode": 400
}
```

2023-10-28 09:04 UTC, kangssu requested changes

2023-10-28 09:04 UTC, kangssu commented on src/feature/user/dto/createUser.dto.ts
> +  //@IsStrongPassword()
주석일까용? 사용하지 않는 코드 주석은 전부 삭제 부탁드려용!

2023-10-28 09:04 UTC, kangssu commented on src/feature/user/user.controller.ts
> +    private readonly userRepository: UserRepository,
Controller에 Repository 주입보다는 Service에 Repository 주입으로 변경하는건 어떨까요?
Controller -> Service -> Repository 흐름으로용 😄

2023-10-28 09:04 UTC, kangssu commented on src/feature/user/user.controller.ts
> +    const userExist = await this.userRepository.findOneByUsername(username);
userRepository를 바로 호출하는 것이 아닌 this.userService.findOneByUsername으로 연결해주세용!

userExist 변수명은 유저 존재함의 뜻인 것 같은데용! 
없을 수도 있다는 것을 가정한다면 맞지 않을 것 같다는 생각이들어요!

const user = 이렇게만 하면 일단 user를 담을텐데 아래 if문에서 if(!user) 이런식으로 유저가 존재하지 않는다!로 작성하는 것이 좋을 것 같습니다!

2023-10-28 09:04 UTC, kangssu commented on src/feature/user/user.controller.ts
> +    await this.userService.createUser(createUserDto);
await this.authService.createAuthCode(email);
await this.userService.createUser(createUserDto);

이렇게 2개로 분리하신 이유가 있을까용?
결국 회원가입할때 이메일 코드가 발송되어서 저장되는 방식이라면,
userService.createUser 안에서 인증코드를 저장하는 것이 좋을 것 같다고 생각합니다!
이렇게 간다면 await this.authService.createAuthCode(email); 이 코드는 Controller에서 삭제해도 좋을 것 같습니당

2023-10-28 09:04 UTC, kangssu commented on src/feature/user/user.controller.ts
> +    const { username, email, password } = createUserDto;
이렇게 분리하는 것보다 createUserDto 자체를 각각의 서비스에 넘기는건 어떨까요?
예를들면 아래 코드처럼한다면 코드가 한줄 더 줄 수 있을 것 같아요 😮 
```
this.userService.findOneByUsername(createUserDto);
// 또는
this.userService.findOneByUsername(createUserDto.username);
```

2023-10-28 09:04 UTC, kangssu commented on src/feature/user/user.service.ts
> +    const user = this.userRepository.create({
{ username, email, password }: CreateUserDto 이렇게 나눈 이유가 있을까요?
만약 이렇게 나누지 않고 creatrUserDto: CreatureUserDto 로 간다면 더 깔끔하고 아래 코드도 줄일 수 있을 것 같다고 생각합니당
```
const user = this.userRepository.create(creatrUserDto);
```

근데 궁금한게 있는데요! 여기서 create랑 save 두번하는게.. 중복되는 것 같아요!

만약 userRepository.create로 넘어가서 저장을 한다면 save는 Repository 안에 들어가있어야해요!
그리고 혹시 여기선 아래 예시 코드처럼 save 바로 작성안될까요? 
지금 특별한 로직이 없는데 저장하는걸로 코드가 몇줄이 나와서 아래처럼 하면 한줄이면 끝나요!
```
async createUser(creatrUserDto: CreateUserDto) {
  return await this.userRepository.save(creatrUserDto);
}
```

2023-10-28 09:04 UTC, kangssu commented on src/feature/user/user.service.ts
> +    const characterTypes = [
이게 어떤 역할을 하는 걸까요? 패스워드에 대한 문자열 타입을 인증하는걸까요? 잘 이해하지 못했습니당 😓 

그리고 패스워드 제약조건은 뭐뭐 사용하셨는지 알 수 있을까요?
한가지 더 의견을 드리자면, 
회원가입시 비밀번호, 비밀번호 확인 추가해서 Bcrypt 에 비교하는 것도 사용해보면 좋을 것 같긴 합니당 😄

2023-10-28 09:04 UTC, kangssu commented on src/feature/user/user.controller.ts
> +    const passwordValid =
passwordValid 여기에 담기는 값은 true, false 둘 중 하나가 맞나용?
맞다면, boolean 타입의 경우 is를 앞에 붙인다고 해용 boolean 타입인 true 나 false를 반환한다는 변수를 알 수 있게 가는게 어떨까요?
https://www.crocus.co.kr/1638

2023-10-28 09:20 UTC, dawwson requested changes
고생하셨습니다! 리뷰 확인 부탁드려요!

2023-10-28 09:20 UTC, dawwson commented on src/feature/user/user.controller.ts
> +    }
400 에러는 요청 형식이 부적절할 때 사용하는 것이 좋아보입니다. 예를 들어 아이디를 string으로 받아야 하는데 number로 받았다던지...(주로 dto에서 걸러지는 경우...)
아이디가 중복되는 에러라면 409 Conflict가 좀 더 적합해보여요!

2023-10-28 09:20 UTC, dawwson commented on src/feature/user/user.service.ts
> +    }
이 부분은 createUserDto에서 이미 검사해주고 있네요!

2023-10-28 09:20 UTC, dawwson commented on src/feature/user/user.service.ts
> +    return !/(\w)\1\1/.test(password);
이 부분도 @ Matches() 데코레이터를 사용해서 DTO로 뺄 수 있을 거 같은데, 비즈니스 로직에 작성하신 이유가 있으신가용?

2023-10-28 09:20 UTC, dawwson commented on src/feature/user/user.controller.ts
> +    await this.userService.createUser(createUserDto);
이거 두가지가 하나의 트랜잭션에서 관리되고 있나요? 
[ 사용자 저장 -> 인증코드 생성 및 저장 ] 중 하나만 안 되더라도 rollback 되어야 하지 않나.. 하는 생각입니다. 연관관계가 아닌 테이블 두 개에 insert 쿼리가 두 번 날아가게 되니까요!

2023-10-28 09:20 UTC, dawwson commented on src/feature/user/user.controller.ts
> +    }
그리고 이 부분도 service에서 하는 건 어떠세요? 
자원을 단순히 조회만 하는 API(service에서 조회된 값을 리턴해주는 일밖에 하지 않는 경우)가 아니라면 repository는 service에서만 사용하는 게 깔끔하다고 생각합니다!

2023-10-28 09:20 UTC, dawwson commented on src/auth/auth.service.ts
> +    );
console.log()는 지워야 할 것 같습니다!

여기 type assertion을 쓰신 이유가 있나요? create() 함수로 AuthCode 엔티티가 생성될 거 같은데요!

2023-10-28 09:50 UTC, tomeee11 approved these changes

2023-10-28 10:42 UTC, laetipark commented on src/feature/user/user.controller.ts
> +    private readonly userRepository: UserRepository,
넵 repository 사용하는 메서드가 하나 뿐이라 service에 넣겠습니다!

2023-10-28 10:53 UTC, laetipark commented on src/feature/user/user.controller.ts
> +    await this.userService.createUser(createUserDto);
아래 은수님 말씀처럼 회원가입할 때 인증코드와 사용자 정보 저장을 함께 하는 게 좋을 거 같네요!

2023-10-28 11:07 UTC, laetipark commented on src/feature/user/user.service.ts
> +    const user = this.userRepository.create({
여기 부분은 create작업이 필요해 보이는 게, 암호화 작업 때문에 그렇습니다!
user entity에 비밀번호 암호화 관련 코드 작성했는데, 그냥 save하면 DB에 암호화 처리가 되지 않더라고요 😢

```typescript
  @BeforeInsert()
  @BeforeUpdate()
  private async beforeInsert() {
    this.password = await bcrypt.hash(this.password, 10);
  }
```

2023-10-28 11:14 UTC, laetipark commented on src/feature/user/user.controller.ts
> +    }
409랑 400이랑 어떤 걸 사용할 지 잘 몰라서 고민했는데, 409로 사용하겠습니다!
그리고 throw 관련은 service에 다룰게요 :)

2023-10-28 11:18 UTC, laetipark commented on src/feature/user/user.service.ts
> +    const characterTypes = [
방식은 `비밀번호 10자 이상`, `숫자, 문자, 특수문자 2가지 이상 사용` 그리고 `3회 이상 연속되는 문자 사용 금지` 사용했습니다.
은수님 의견을 더해서 에러 응답 코드로 표현하려 하는데, 필요하다면 주석까지 작성하겠습니다!

```typescript
if (characterTypes < 2) {
  throw new ConflictException(
    `숫자, 문자, 특수문자 중 2가지 이상을 포함해야하 합니다.`,
  );
}

if (/(\w)\1\1/.test(password)) {
  throw new ConflictException(
    `3회 이상 연속되는 문자 사용은 불가능합니다.`,
  );
}
```

그리고 비밀번호 확인 부분을 추가로 body에 받아서 하는 게 좋을까요?

2023-10-28 11:30 UTC, laetipark commented on src/feature/user/user.service.ts
> +    return !/(\w)\1\1/.test(password);
위에는 `숫자, 문자, 특수문자 2가지 이상 사용` 개수를 확인하는 거고 아래는 `3회 이상 연속되는 문자 사용 여부`를 확인하는 건데, 아래는 Matches 데코레이터로 구현이 가능할 거 같은데 위에는 정규식으로 작성할 수 있는 지 모르겠네요.
나머지 코드 수정해보고 확인해보겠습니다!

2023-10-28 14:44 UTC, kangssu commented on src/feature/user/user.service.ts
> +    const characterTypes = [
@laetipark 
아 방식에 대해 위에 설명해놓으셨는데 다른 부분인 줄 알았어요! 답변 감사해요 😄 
응답 코드도 좋은 생각인 것 같아요! 그리고 비밀번호 확인 부분은 시간되면 나중에 해보셔도 되용 Dto에 추가로 받아서 사용하면 되긴 합니다!

2023-10-29 08:39 UTC, kangssu approved these changes

2023-10-29 09:31 UTC, dawwson approved these changes
리뷰 반영하신 부분 확인했습니다. 코멘트 한 개만 더 확인 부탁드려요!
추가하신 비밀번호 확인 로직은 README에도 적어두면 좋을 거 같네요. 
고생하셨습니다!

2023-10-29 09:31 UTC, dawwson commented on src/feature/user/user.service.ts
> +    }
이 부분은 400 Bad Request로 처리하는 것이 좋겠습니다!

2023-10-29 11:48 UTC, sayapin1 approved these changes
고생하셨습니당!

2023-10-29 11:52 UTC, tomeee11 approved these changes

2023-10-29 12:45 UTC, merged