게시물 좋아요 API
Wanted-Pre-Onboarding-Team-E/social-media-integration-feed pull request #19
Opened 2023-10-28 11:43 UTC by tomeee11

## 🚀 이슈 번호
<br>
#15 게시물 좋아요 API

## 💡 변경 이유
<br>

![조와요](https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/114478045/5ad63f16-705c-41e4-b056-a1836c49c038)

## 🔑 주요 변경사항
<br>

위와 동일

## 📷 테스트 결과

![조와요2 없음](https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/114478045/7b9291af-82e3-4617-9542-082fb43b4056)

2023-10-28 12:29 UTC, kangssu requested changes

2023-10-28 12:29 UTC, kangssu commented on src/feature/post/post.controller.ts
> +    @Param('postId') postId: number,
파람으로 받는거면 Pipe에서 숫자인지의 여부 검증하는거 추가하는건 어떨까요? 😮
NestJS에 Pipe 관련 문서있습니당

2023-10-28 12:29 UTC, kangssu commented on src/feature/post/post.service.ts
> +    await this.postRepository.incrementPostLikeCount(type, postId);
로직이 조금 추가되어야 할 것 같아요. 요구사항에는 아래 2가지 조건이 들어있어용!
1. 각각의 외부 sns API 호출 
(예시 : 인스타그램에서 넘어온 게시물에 좋아요 표시시 https://www.instagram.com/likes/<content_id> 이 호출됨)
2. 해당 호출이 성공할 시 response status 200 해당 게시물의 like_count가 1 증가합니다.

2023-10-28 12:29 UTC, kangssu commented on src/feature/post/repository/post.repository.ts
> +      .set({ likeCount: () => 'likeCount + 1' })
만~~~약에 postId && type 조건에 맞는 데이터가 없다면.. 예외처리를 해주는것이 좋지 않을까요?

그리고 제가 `.set({ likeCount: () => 'likeCount + 1' })` <- 요 방식으로 사용을 해본적이 없어서 궁금한 점이 있습니당
예를들어 postId 1번인 게시글에 likeCount가 5로 데이터가 들어가있을 경우,
위 쿼리를 실행한다면 postId 1번인 게시글에 likeCount가 6으로 업데이트 되는게 맞을까요? 😮

2023-10-28 23:58 UTC, tomeee11 commented on src/feature/post/repository/post.repository.ts
> +      .set({ likeCount: () => 'likeCount + 1' })
저도 이 방식을 아직 설명을 못하겠는데
likeCount + 1 이렇게 넣었을 때와 likeCount: () => 'likeCount + 1 넣었을 떄
많은 트래픽이 발생했을 떄 likeCount + 1 일 경우 디비락이 걸리더라구요

2023-10-29 01:16 UTC, laetipark approved these changes
고생 많으십니다! 제가 추가로 확인한 코드 수정할 부분은 없는 거 같아 승인합니다. 코드 잘 보고 갑니다 😸

2023-10-29 01:16 UTC, laetipark commented on src/feature/post/post.controller.ts
> +    @Param('postId') postId: number,
저도 공부해봐야겠네요! 📝👀

2023-10-29 01:16 UTC, laetipark commented on src/feature/post/repository/post.repository.ts
> +      .set({ likeCount: () => 'likeCount + 1' })
저도 위와 같은 코드 구현해본 적 있는데, 저러한 방식으로 들어가는 것이 맞아요!
```sql
update post set like_count = like_count + 1 where ...;
```

2023-10-29 08:47 UTC, kangssu requested changes

2023-10-29 08:47 UTC, kangssu commented on src/feature/post/post.app.module.ts
> +  providers: [PostService, PostRepository],
PostRepository가 providers에서 이제 사라져야할 것 같아요!
아직 repository 폴더가 남아있네용 오전에 회의한대로 repository도 전부 수정 부탁드려요!

2023-10-29 08:47 UTC, kangssu commented on src/feature/post/post.controller.ts
> +    @Param('postId') postId: number,
@tomeee11 
Pipe 관련 인증은 아직 수정이 안된걸까요? 😮 (다시 풀리퀘 해주신 것 같아서요!)

2023-10-29 08:47 UTC, kangssu commented on src/feature/post/repository/post.repository.ts
> +export class PostRepository {
저희 Repository 분리 안하기로 결정났었는데 아직 분리된걸로 보이네용!

2023-10-29 08:47 UTC, kangssu commented on src/feature/post/repository/post.repository.ts
> +    if (response.status === 200) {
제 PR에 은수님 코멘트를 보신 것 같긴했는데 아래 부분은 놓친 것 같아요!
원래는 catchError에서 Exception 으로 터뜨리거나 해야하는데 저희는 어차피 전부 다 실패여서
catchError에 카운트 증가하는 로직을 넣어버리고 노트 주석으로 기록해두는걸로 수정 부탁드려요! 😄 
```
this.httpService.post('http://www.facebook.com/share').pipe(
        catchError((error: AxiosError) => {
          /*
          NOTE: 가상의 URL이기 때문에 반드시 에러가 발생합니다. 
                따라서 이 요청이 status 200 성공 응답을 받았다고 
                가정하고 catchError 내부에 작성합니다.
          */
          await this.postRepository.save({ ...poat, shareCount: +1 });
          return ;
        }),
      ),
```

2023-10-29 08:47 UTC, kangssu commented on src/feature/post/repository/post.repository.ts
> +      .set({ likeCount: () => 'likeCount + 1' })
오 새로운 방식 얻어갑니당! 검색해봐야겠네요 👍

2023-10-29 11:11 UTC, tomeee11 commented on src/feature/post/repository/post.repository.ts
> +    if (response.status === 200) {
위와 같이 추가적인 회의 내용은 제가 모르는 상황이었고 풀리퀘 보냈고 
말씀 드리긴 했는데, 추후에 에러 핸들링 방식이나 발리데이션 파이프를, dto에 쓸지 entity에 쓸지 정해지면 한번에 
수정하려고 했다고 말씀드렸는데, 
일단 수정을 할까요 ??

2023-10-29 11:51 UTC, laetipark approved these changes
고생 많으십니다! 제가 추가로 확인할 코드가 없는 거 같아 승인 처리합니다 :) 좋은 밤 되세요!

2023-10-29 11:53 UTC, kangssu commented on src/feature/post/repository/post.repository.ts
> +    if (response.status === 200) {
@tomeee11 
엇 제가 말씀 드린 부분은 아래 내용을 말씀드린게 아니예요! 😮 
"추후에 에러 핸들링 방식이나 발리데이션 파이프를, dto에 쓸지 entity에 쓸지 정해지면..."

저희 외부 호출하는 방식인 httpModule 관련 내용을 드린거였어요! 
* NestJS 공식문서 : https://docs.nestjs.com/techniques/http-module#full-example

풀리퀘에 httpModule이 포함되어 있길래 아래 팀 DM 내용을 확인하신 줄 알았습니당 😅
아래 부분만 수정해주시면 될 것 같습니다!
![이미지 4](https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/83870420/f93e7f57-547a-47f6-bd7c-5bee262285c4)

2023-10-30 00:55 UTC, dawwson approved these changes

2023-10-30 00:58 UTC, sayapin1 approved these changes

2023-10-30 00:58 UTC, laetipark approved these changes

2023-10-30 00:59 UTC, kangssu approved these changes

2023-10-30 01:02 UTC, kangssu approved these changes

2023-10-30 01:03 UTC, sayapin1 approved these changes

2023-10-30 01:21 UTC, merged