사용자 로그인 API
Wanted-Pre-Onboarding-Team-E/social-media-integration-feed pull request #9
Opened 2023-10-26 20:30 UTC by dawwson

## 🚀 이슈 번호
https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/issues/8#issue-1963458598
<br>

## 💡 변경 이유
- 사용자 로그인 API 추가
<br>

## 🔑 주요 변경사항
<img width="487" alt="image" src="https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/45624238/5127929f-7676-4b54-b03a-1f05c006f956">

### 1. Passport 적용  ( => 이 부분은 @kangssu 님의 레포를 많이 참고하였습니다👍)
- **(로그인, 회원가입, 가입승인 제외)** 사용자 인증이 필요한 엔드포인트에 `@UseGuards(JwtAuthGuard)`데코레이터를 붙이고 사용하시면 됩니다.
- `Cookie` 헤더에 있는 `JWT` 토큰을 검증하고 유효하다면 `req.user`에 `User` 객체를 붙여줍니다.
- **예시**
  <img width="671" alt="image" src="https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/45624238/2e9c2aa8-be13-4261-8637-21279d7fd44c">

### 2. 로그인 API 추가
- 성공시 `Set-Cookie` 헤더에 `JWT` 토큰이 담깁니다.
- 실패시 401 에러를 반환합니다.
- 토큰 생성시 페이로드는 임의로 `id`, `username`만 넣었습니다.

### 3. 환경변수 추가
- `.env` 파일에 `JWT_SECRET`을 추가하면 됩니다

### 4. `Controller`, `Service`, `Repository` 단위 테스트 작성
- `unit` 이라는 폴더 아래에 `controller`, `service`, `repository` 폴더를 나눠놨습니다.
- `DB`에 접근하지 않고 각 레이어에서 필요한 의존성들은 모킹하도록 만들었습니다.

<br>

## 📷 테스트 결과
### 단위 테스트 결과
<img width="376" alt="image" src="https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/45624238/4396c77b-870e-4a56-a147-552258f4addd">

### HTTP 요청 테스트 결과
<img width="931" alt="image" src="https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/45624238/a5967991-26c9-400d-8047-c93871b27205">
<img width="933" alt="image" src="https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/45624238/021a2bf3-7430-4d60-8ed0-59d798f6f209">

2023-10-27 00:39 UTC, tomeee11 approved these changes

2023-10-27 00:59 UTC, kangssu requested changes

2023-10-27 00:59 UTC, kangssu commented on src/auth/auth.module.ts
> +  providers: [AuthService, JwtStrategy, UserLib, UserRepository],
UserLib, UserRepository를 빼고 UserModule을 imports에 넣어주시는게 좋을 것 같아요!

2023-10-27 00:59 UTC, kangssu commented on src/feature/user/user.app.module.ts
> +      secret: process.env.JWT_SECRET,
JWT_SECRET 관련은 제 생각에는 auth.module.app.ts 파일에 넣는게 맞을 것 같습니다!
그 이유는 JWT_SECRET은 jwt 관련인데 user가 아닌 auth와 연관있어보입니다!

토큰 7일 저장 괜찮을까요..? 보안상을 위해 좀 더 짧게 지정해도 괜찮을 것 같아요!

2023-10-27 00:59 UTC, kangssu commented on src/feature/user/user.controller.ts
> +    return res.cookie('accessToken', accessToken, { httpOnly: true }).send();
리턴할때 accessToken이랑 user 정보(payload) 같이 리턴해줘야 하지 않나요?
추후에 프론트딴에서 유저 정보랑 토큰이 같이 필요할 것 같습니다!

2023-10-27 00:59 UTC, kangssu commented on src/auth/auth.service.ts
> +  constructor() {}
Auth 서비스에 토큰 생성등을 옮기는게 낫지 않을까요?
auth랑 user랑 속성이 다르다고 생각이 들어서 auth 관련된거는 auth 파일들에 넣는게 좋다고 생각합니다!

2023-10-27 00:59 UTC, kangssu commented on src/auth/strategy/jwt.strategy.ts
> +  async validate(payload: { id: number; username: string }) {
여기 혹시 유저 정보에 패스워드도 들어오진 않나요?
패스워드는 중요한 정보라 여기서 리턴해줄때 제외하고 보내주는건 어떤가요??

2023-10-27 00:59 UTC, kangssu commented on src/feature/user/user.lib.ts
> +  getById(id: number): Promise<User> {
get 가져올때 어떤 것을 가져오는지를 명시하는게 좋을 것 같아요! getUserById 이런식으로요!

2023-10-27 00:59 UTC, kangssu commented on src/feature/user/user.controller.ts
> +    const { username, password } = loginRequestDto;
이 코드를 생략하는건 어떠세요??
아래 코드에 const verifiedUser = await this.userService.verifyUser(loginRequestDto); 이런식으로 넘기고
서비스에서 loginRequestDto로 한번에 받으면 조금 더 간결해질 것 같아서요!

2023-10-28 02:15 UTC, dawwson commented on src/auth/auth.module.ts
> +  providers: [AuthService, JwtStrategy, UserLib, UserRepository],
오 그렇네요.. 지금 보니까 nest가 모듈화로 프로바이더를 캡슐화하는 걸 권장하고 있네요
<img width="795" alt="image" src="https://github.com/Wanted-Pre-Onboarding-Team-E/social-media-integration-feed/assets/45624238/16e5f6ec-281a-4cca-825c-6cfde8c1cc98">

2023-10-28 02:25 UTC, dawwson commented on src/feature/user/user.app.module.ts
> +      secret: process.env.JWT_SECRET,
- 넵 auth 모듈에서 jwt 관련 작업할 수 있도록 리팩터 해보겠습니다~!
- 그러게요... 보통 리프레시 토큰의 유효 기간을 길게 주고 액세스 토큰은 분이나 시간 단위로 주는 거 같네요. 다음 링크 참조해서 24시간 정도로 수정하겠습니다! https://developers.worksmobile.com/kr/docs/auth-jwt

2023-10-28 04:36 UTC, dawwson commented on src/feature/user/user.controller.ts
> +    return res.cookie('accessToken', accessToken, { httpOnly: true }).send();
id, username, email 정도만 리턴해주면 되려나요...??

2023-10-28 04:41 UTC, dawwson commented on src/auth/strategy/jwt.strategy.ts
> +  async validate(payload: { id: number; username: string }) {
네 지금은 패스워드가 들어갑니다. 수정해둘게요!

2023-10-28 05:29 UTC, dawwson commented on src/auth/auth.service.ts
> +  constructor() {}
user 컨트롤러에서 auth 컨트롤러로 엔드포인트를 이동하면서 jwt 모듈도 auth 모듈로 이동하였는데, 이렇게 하면 컨트롤러에서 JwtService를 바로 가져와서 사용하는 게 좋을 거 같습니다! 어떤지 코드로 한 번 봐주시면 감사하겠습니다!

2023-10-28 06:26 UTC, dawwson commented
**[ 리뷰 반영 및 변경된 내용 ]**

**1. 엔드포인트 변경 : `/users/login` -> `/auth/login`**
  - `Jwt` 모듈을 `Auth` 모듈로 옮기다보니 엔드포인트부터 적절하지 않았다는 생각이 들어서 수정했습니다.
  - 관련 수정사항
    - `Jwt` 모듈을 `AuthModule`로 `import` 하였음
    - `UserService`에 있던 사용자 검증 로직을 `AuthService`로 이동
    - JwtStrategy 내부에서 사용중인 getUserById() 함수는 UserLib로 이동

**2. 로그인 응답 바디 수정**
   - 사용자 정보(id, username, email) 담아서 리턴

**3. JWT 토큰 만료시간 24h로 수정**

**4. repository 분리하지 않고 서비스에서 바로 주입하도록 수정**

**5. user repository 테스트 코드 삭제**

2023-10-28 06:54 UTC, kangssu commented on src/feature/user/user.controller.ts
> +    return res.cookie('accessToken', accessToken, { httpOnly: true }).send();
@dawwson 넹넹! 충분할 것 같습니다 👍

2023-10-28 06:59 UTC, kangssu commented on src/auth/auth.service.ts
> +  constructor() {}
@dawwson 네! 좋은 것 같습니다 😄 
+ user 컨트롤러에서 작업되있던 것들 auth로 변경된 부분 전부 확인하였습니당!

2023-10-28 08:20 UTC, kangssu approved these changes

2023-10-28 08:23 UTC, laetipark approved these changes

2023-10-28 08:23 UTC, laetipark commented on src/auth/auth.module.ts
> +  providers: [AuthService, JwtStrategy, UserLib, UserRepository],
풀 리퀘스트 확인하고 저도 auth 폴더를 src 다음에 두긴 했는데, feature영역과는 다르게 보는 게 맞을까요? 감이 잘 안 잡혀서 질문드립니다!

2023-10-28 08:32 UTC, dawwson commented on src/auth/auth.module.ts
> +  providers: [AuthService, JwtStrategy, UserLib, UserRepository],
그렇네요...
그러면 auth 모듈(컨트롤러+서비스+dto)을 feature 내부로 옮기고, jwt strategy와 jwt guard를 src 하위의 custom? 폴더로 옮길까요?
src
- custom
  - strategy
    - jwt.starategy.ts
  - guard
    - jwtAuth.guard.ts
- feature
  - auth
    - dto
    - auth.controller.ts
    - auth.module.ts
    - auth.service.ts

2023-10-28 08:43 UTC, sayapin1 approved these changes

2023-10-28 09:49 UTC, dawwson commented on src/auth/auth.module.ts
> +  providers: [AuthService, JwtStrategy, UserLib, UserRepository],
controller가 있는데 feature 바깥에 있는 게 이상하긴 하네요...! 일단 이 부분은 리팩터 할 때 다시 생각해보겠습니다!

2023-10-28 09:49 UTC, merged